import os
import json
import torch
import typing
from pathlib import Path
from torch.utils.data import Dataset, DataLoader


def load_config(config_path: typing.Optional[str] = None) -> typing.Dict[str, typing.Any]:
    """
    Loads the centralized tabular JSON configuration.
    Defaults to tabular/config.json if not specified.
    """
    if config_path is None:
        repo_root = Path(__file__).resolve().parents[2]
        config_path = os.path.join(repo_root, "tabular", "config.json")
    
    if os.path.exists(config_path):
        with open(config_path, "r") as f:
            return json.load(f)
    return {}


class TabularDataset(Dataset):
    """
    A simple map-style Dataset that loads precomputed episodic tasks
    from the .pt files generated by Preprocessing.py.
    """
    def __init__(self, data_path: str):
        """
        Args:
            data_path (str): Path to the .pt file (e.g., 'dataset_prepro_routine_generated_train_tasks.pt')
        """
        self.episodes = torch.load(data_path, weights_only=False)
        
        # Preload the entire dataset directly onto the GPU VRAM if available
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        for i in range(len(self.episodes)):
            self.episodes[i]['x_s'] = self.episodes[i]['x_s'].to(device)
            self.episodes[i]['y_s'] = self.episodes[i]['y_s'].to(device)
            self.episodes[i]['x_q'] = self.episodes[i]['x_q'].to(device)
            self.episodes[i]['y_q'] = self.episodes[i]['y_q'].to(device)

    def __len__(self) -> int:
        return len(self.episodes)
        
    def __getitem__(self, idx: int) -> typing.Dict[str, torch.Tensor]:
        """
        Returns a dictionary containing:
            x_s (Tensor): Support set features
            y_s (Tensor): Support set labels
            x_q (Tensor): Query set features
            y_q (Tensor): Query set labels
            task_id (int): ID of the task
        """
        return self.episodes[idx]


def tabular_train_val_split(eps_data: typing.Dict[str, torch.Tensor], **kwargs) -> typing.Dict[str, torch.Tensor]:
    """
    Split function to seamlessly integrate with MLBaseClass and Maml architectures.
    Maps support (s) -> train (t) and query (q) -> validation (v).
    """
    return {
        'x_t': eps_data['x_s'].squeeze(0),
        'y_t': eps_data['y_s'].squeeze(0),
        'x_v': eps_data['x_q'].squeeze(0),
        'y_v': eps_data['y_q'].squeeze(0),
    }


def get_tabular_dataloader(data_path: str, shuffle: bool = True) -> DataLoader:
    """
    Convenience function to get the dataloader for the tabular tasks.
    Batch size is strictly 1 because MLBaseClass/Maml processes one task at a time 
    in the inner loop logic.
    """
    dataset = TabularDataset(data_path)
    return DataLoader(dataset, batch_size=1, shuffle=shuffle)
